# Generated by Django 3.2.9 on 2021-11-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0002_friendlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='is_active',
            new_name='is_pending',
        ),
    ]
